### ISSUE TITLE
Missing illustrations.

### ISSUE THREAD

**Issue by kpmgeek** [standardebooks/a-a-milne_winnie-the-pooh#2]
Project Gutenberg's epub version includes the beautiful original illustrations which are omitted here.

**Comment by acabal** [comment]
We don't include decorative illustrations in our ebooks as a general rule. Sorry!

**Comment by kpmgeek** [comment]
That's not consistently implemented then as your Alice In Wonderland does.

**Comment by acabal** [comment]
Indeed, that ebook was produced before the rule went into effect. It's part of the reason why we have the rule, as _Alice_ has been re-illustrated repeatedly over the past century and a half.

**Comment by astrowonk** [comment]
> Indeed, that ebook was produced before the rule went into effect. It's part of the reason why we have the rule, as _Alice_ has been re-illustrated repeatedly over the past century and a half.

I see some sense in this but the original Ernest H. Shepard illustrations are iconic and very much a part of the original work. The main use case of the book would be to read it to children, who want to see the pictures. I think it's worth considering changing the rule for the original illustrations.

**Comment by daviewales** [comment]
I feel that exceptions should be made for original images which are iconic and contribute significantly to the character of the work. Leaving the illustrations out of Winnie the Pooh is like including only odd-numbered pages!

**Comment by daviewales** [comment]
Having said that, I have just looked at the illustrations for Alice, and am extremely impressed by their incredibly high quality. The are SVGs, and seem like they could scale infinitely. I'm guessing that's a lot of work. But if the effort required is the barrier, rather than a vision for the final output, then I feel that it should be a case of "Contributions welcome, but we don't have time ourselves" rather than "no images ever".

**Comment by jonatanskogsfors** [comment]
The license used for this repo should allow it to be forked by anyone to include the illustrations downstream. I'm not familiar with the tool chain used by standardebooks, e.g. if it also would need modifications or be replace with something else. Built files (epub etc) could be hosted on github as release artefacts.

**Comment by acabal** [comment]
This work is in the US public domain, and our work is released via CC0, so anyone in the US can do anything they want with it, without asking, including forking it. Forking does not require some kind of special license in this case.

**Comment by jonatanskogsfors** [comment]
I read that one of you missions is exactly this, to provide starting points for other ebooks. That is super nice!

Just out of curiosity, is the rule about illustrations documented somewhere on the site? I tried to find it but only found some references to how illustrations should be included.

**Comment by acabal** [comment]
I don't know off the top of my head, the website and manual are big. But that's the general rule and I'm in charge of reminding people of that.
